### ISSUE TITLE
GitLab integration

### ISSUE THREAD

**Issue by Bishop** [integrity/integrity#265]
Are you interested in [GitLab](https://about.gitlab.com) integration?

**Comment by automaticgiant** [comment]
I'm having no joy with autobranch. It looks like the tests cover this case, but I'm not getting it. Is it a limitation of GitLab hooks?

**Comment by Bishop** [comment]
It need more details. Could you create issue and describe problem with more details: content of your config `local.rb`, gitlab version etc.
